import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import '../styles/globals.css'
import { UserProvider } from '@/contexts/UserProvider'
import 'material-icons/iconfont/material-icons.css'

// Assuming Poppins is available, you can replace the following line
const poppins = Poppins({ weight: ['400'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SocialMate',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  )
}
